catalog/urls.py
"""
from django.conf.urls.defaults import *

urlpatterns += patterns('catalog.views',
    #(r'^$', 'index', { 'template_name':'catalog/index.html'}, 'catalog_home'),
    (r'^category/(?P<category_slug>[-\w]+)/$','show_category', {'template_name':'catalog/category.html'},'catalog_category'),
    (r'^product/(?P<product_slug>[-\w]+)/$','show_product', {'template_name':'catalog/product.html'},'catalog_product'),
)
"""

ecommerce/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.defaults import *
from ecommerce import settings
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    (r'^accounts/', include('registration.backends.default.urls')),
    url(r'^checkout/', include('checkout.urls')),

    #url(r'^$', include('catalog.urls')),
    # Examples:
    # url(r'^$', 'ecommerce.views.home', name='home'),
    # url(r'^ecommerce/', include('ecommerce.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:

)


urlpatterns += patterns('accounts.views',
        (r'^register/$', 'register'),
        (r'^$', 'home'),
        (r'^about/$', 'about'),
        (r'^logout/$', 'logout'),
        (r'^accounts/profile/$', 'my_account',
        {'template_name': 'registration/my_account.html'}, 'my_account'),


)
"""urlpatterns += patterns('accounts.views',
        (r'^register/$', 'register',
        {'template_name': 'registration/registration.html'},
        'register'),

        (r'^my_account/$', 'my_account',
        {'template_name': 'registration/my_account.html'}, 'my_account'),

        (r'^order_details/(?P<order_id>[-\w]+)/$', 'order_details',
        {'template_name': 'registration/order_details.html'}, 'order_details'),

        (r'^order_info//$', 'order_info',
        {'template_name': 'registration/order_info.html'}, 'order_info'),
)
    """


urlpatterns += patterns('',
        (r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'registration/login.html'}, 'login'),

        (r'^password_change/$', 'django.contrib.auth.views.password_change',
        {'template_name': 'registration/password_change.html'}, 'password_change'),

)

urlpatterns += patterns('contact.views',
                       url(r'^contact$', 'contact'),
)

urlpatterns += patterns('catalog.views',
    #(r'^$', 'index', { 'template_name':'catalog/index.html'}, 'catalog_home'),
    (r'^category/(?P<category_slug>[-\w]+)/$','show_category', {'template_name':'catalog/category.html'},'catalog_category'),
    (r'^product/(?P<product_slug>[-\w]+)/$','show_product', {'template_name':'catalog/product.html'},'catalog_product'),
)

urlpatterns += patterns('cart.views',
    (r'^cart$', 'show_cart', { 'template_name': 'cart/cart.html' }, 'show_cart'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    name        = models.CharField(max_length=50)
    slug        = models.SlugField(max_length=50, unique=True, help_text='Unique value for product page URL, created from name.')
    description = models.TextField()
    is_active   = models.BooleanField(default=True)
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)

    class Meta:
        db_table            = 'categories'
        ordering            = ['name', ]
        verbose_name_plural = 'Categories'

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('catalog_category', (), {'category_slug': self.slug})


class Product(models.Model):
    name          = models.CharField(max_length=50, unique=True)
    price         = models.DecimalField(max_digits=9, decimal_places=2)
    old_price     = models.DecimalField(max_digits=9, decimal_places=2, blank=True, default=0.00)
    slug          = models.SlugField(max_length=255, unique=True, help_text='Unique value for product page URL, created from name.')
    image         = models.ImageField(upload_to='photos/', blank=True)
    is_active     = models.BooleanField(default=True)
    is_featured   = models.BooleanField(default=True)
    is_bestseller = models.BooleanField(default=False)
    quantity      = models.IntegerField()
    description   = models.TextField()
    created_at    = models.DateTimeField(auto_now_add=True)
    update_at     = models.DateTimeField(auto_now=True)
    categories    = models.ManyToManyField(Category)

    class Meta:
        db_table = 'products'
        ordering = ['-created_at']

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('catalog_product', (), {'product_slug': self.slug})

    def sale_price(self):
        if self.old_price > self.price:
            return self.price
        else:
            return None

contact/models.py
from django.db import models

# Create your models here.

catalog/forms.py
import floppyforms as forms
from models import Product


class ProductAdminForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('created_at', 'update_at',)

    def clean_price(self):
        if self.cleaned_data['price'] <= 0:
            raise forms.ValidationError('Price must be greater than zero')
        return self.cleaned_data['price']


class ProductAddToCartForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=100, widget=forms.NumberInput(attrs={'size': 2, 'value': 1, 'class': 'quantity'}))
    product_slug = forms.CharField(widget=forms.HiddenInput())

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        super(ProductAddToCartForm, self).__init__(*args, **kwargs)

    def clean(self):
        if self.request:
            if not self.request.session.test_cookie_worked():
                raise forms.ValidationError("Cookies must be enabled.")
        return self.cleaned_data

contact/forms.py
from django import forms


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label='Your e-mail address')
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words")
        return message

catalog/views.py
from django.shortcuts import render_to_response, get_object_or_404, redirect
from catalog.models import Category, Product
from django.template import RequestContext
from django.core import urlresolvers
from cart import cart
from forms import ProductAddToCartForm


def index(request, template_name="catalog/index.html"):
    title = "Index"
    return render_to_response(template_name, locals(), context_instance=RequestContext(request))


def show_category(request, category_slug, template_name="catalog/category.html"):
    c = get_object_or_404(Category, slug=category_slug)
    products = c.product_set.all()
    title = c.name

    return render_to_response(template_name, locals(), context_instance=RequestContext(request))


def show_product(request, product_slug, template_name="catalog/product.html"):
    p = get_object_or_404(Product, slug=product_slug)
    categories = p.categories.filter(is_active=True)
    title = p.name
    if request.method == "POST":
        postdata = request.POST.copy()
        form = ProductAddToCartForm(request, postdata)
        if form.is_valid():
            cart.add_to_cart(request)
            if request.session.test_cookie_worked():
                request.session.delete_test_cookie()
            url = urlresolvers.reverse('show_cart')
            return redirect(url)
    else:
        form = ProductAddToCartForm(request=request, label_suffix=":")

    form.fields['product_slug'].widget.attrs['value'] = product_slug
    request.session.set_test_cookie()
    return render_to_response("catalog/product.html", locals(), context_instance=RequestContext(request))

contact/views.py
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from contact.forms import ContactForm
from django.template import RequestContext


def contact(request):
    title = "Contact Us"
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                ['siteowner@example.com'],
            )
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = ContactForm(initial={'subject': "I want to request some fish!"})
    return render_to_response('contact_form.html', locals(), context_instance=RequestContext(request))

ecommerce/templates/about.html
{% extends 'base.html' %}
{% block title %}JMD Seafoods | Home{% endblock %}
{% block content %}

	<h3>About Us</h3>

<div class="row">
  <div class="large-12 columns" style="text-align:justify;">

  <h5>About JMD Seafoods</h5>	
  <p>Welcome! JMD Seafoods is the number one fresh and frozen seafood dealer in Manila. This business originated on buying and selling fresh seafoods from Bacolod, and Negros Occidental and then sold to the markets. As the business expands our products were now also delivered to the markets in Manila. Few years later JMD ventured in selling frozen seafoods. And at present JMD Seafoods are selling sliced fish on Robinsons supermarkets. Though frozen fish was introduced on the business, JMD seafoods is still engaged in selling fresh fish which are now dropped in Navotas fish port. </p>

  <h5>Terms and Conditions</h5>

  <h5>Orders:</h5>

  <p>Purchase orders are not valid unless checked out and paid online. Purchaser will not recognize claims based on verbal orders.</p>

  <h5>Delivery Policies / Shipment:</h5>

  <p>Delivery of products is available within Metro Manila only. If delivery is not made by the date indicated in this Order, Purchaser may, in addition to its other rights, cancel this Order, without any liability whatsoever. If in order to comply with Purchaser's required delivery date it becomes necessary for Seller to ship by a more expensive way than specified in this purchase order, any increased transportation costs resulting there from shall be paid for by Seller unless the necessity for such rerouting or expedited handling has been caused by Purchaser.</p>


  <h5>Acceptance-Agreement</h5>
  <p>Seller's commencement of work on the goods subject to this purchase order or shipment of such goods, whichever occurs first, shall be deemed an effective mode of acceptance of this purchase order. Any acceptance of this purchase order is limited to acceptance of the express terms contained on the face and back hereof. Any proposal for additional or different terms or any attempt by Seller to vary in any degree any of the terms of this offer in Seller's acceptance is hereby objected to and rejected, but such proposals shall not operate as a rejection of this offer unless such variances are in the terms of the description, quantity, price, or delivery schedule of the goods, but shall be deemed a material alteration thereof, and this offer shall be deemed accepted by Seller without said additional or different terms.</p>

  <h5>Price and Payment</h5>
  <p>Seller warrants that the prices for the articles sold Purchaser hereunder are not less favorable than those currently extended to any other customer for the same or similar articles in similar quantities. In the event Seller reduces its price for such article during the term of this order, Seller agrees to reduce the prices hereof correspondingly. The price stated in this Order includes all charges for packaging, boxing, crating, special handling, and freight, F.O.B. destination. No modification or adjustment of the stated price may be made without the signed written agreement of Purchaser. If the price is not stated on this Order, the price shall be the lower of: the later price last quoted or paid, or the prevailing market price.</p>

  </div>

</div>

{% endblock %}

ecommerce/templates/base.html
<!DOCTYPE html>
    <head>
        {% load staticfiles %}
            <link rel="stylesheet" href="{% static "reveal/reveal.css" %}">

        <!-- Attach necessary scripts -->
        <script type="text/javascript" src="{% static "reveal/jquery-1.4.4.min.js" %}"></script>
        <script type="text/javascript" src="{% static "reveal/jquery.reveal.js" %}"></script>


         <link rel="stylesheet" href="{% static "css/normalize.css" %}" />
         <link rel="stylesheet" href="{% static "css/foundation.css" %}" />
         <script src="{%static "js/foundation.min.js" %}"></script>
         <script src="{%static "js/vendor/custom.modernizr.js" %}"></script>
         <link rel="shortcut icon" href="static/img/jmd-logo.png">


        <title>JMD Seafoods Inc. - {{ title }}</title>
        {% block scripts %}{% endblock %}
    </head>
    <body>

       <div class="row">
    <div class="large-12 columns">

    <!-- Navigation -->

      <div class="row">
        <div class="large-12 columns">

          <nav class="top-bar">
            <ul class="title-area">
              <!-- Title Area -->
              <li class="name">
                <h1>
                  <a href="/">
                    JMD Seafoods Inc.
                  </a>
                </h1>
              </li>
              <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
            </ul>

            <section class="top-bar-section">
              <!-- Right Nav Section -->
              <ul class="left">
                <li class="divider"></li>
                <li><a href="/">Home</a></li>
                <li class="divider"></li>
                <li><a href="/about">About Us</a></li>
                <li class="divider"></li>
                <li><a href="/contact">Contact Us</a></li>
                <li class="divider"></li>


              </ul>


              <ul class="right">
                <li><a href="/cart">Cart</a></li>
                {% if user.is_authenticated %}
                <li><a href="/accounts/profile">Welcome {{ user.username }}</a></li>
                <li><a href="/logout">Logout</a></li>
                {% else %}
                <li><a href="/login">Login</a></li>
                <li class="divider"></li>
                <li><a href="/accounts/register">Register</a></li>
                {% endif %}


              </ul>
            </section>
          </nav>
          <!-- End Top Bar -->
        </div>
      </div><br><br>

        {% block content %}


        {% endblock %}



      <footer class="row">
        <div class="large-12 columns"><hr />
          <div class="row">

            <div class="large-6 columns">
              <p>&copy; JMD Seafoods Inc.</p>
            </div>

            <div class="large-6 columns">
              <ul class="inline-list right">
                <li><a href="/">Home</a></li>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Contact Us</a></li>

              </ul>
            </div>

          </div>
        </div>
      </footer>

<!-- REVEAL -->

<div id="myModal" class="reveal-modal">
  <center>
    {% with cart_item_count as cart_count %}
    <a href="{% url 'show_cart' %}">
    Shopping Cart
    <br />
    {{ cart_count }} Item{{ cart_count|pluralize }}
    </a>
  {% endwith %}
  <p><a href="/checkout"><button class="button">Checkout</button></a></p>
  <a class="close-reveal-modal">&#215;</a>
  </center>
</div>



</div>
<script src="{%static "js/vendor/zepto.js" %}"></script>
<script src="{%static "js/foundation/foundation.js" %}"></script>
<script src="{%static "js/foundation/foundation.joyride.js" %}"></script>
<script src="{%static "js/foundation/foundation.reveal.js" %}"></script>
<script src="{%static "js/foundation/foundation.dropdown.js" %}"></script>
<script src="{%static "js/foundation/foundation.alerts.js" %}"></script>


</body>
</html>

ecommerce/templates/catalog.html
{% extends "base.html" %}

{% block content %}
    <div id="main">
        <a href="#content" class="skip_link">Skip to main content</a>
    </div>

    <div id="banner">
        [banner here]
        <div class="cart_box">
            [link to cart]
        </div>
    </div>
{% endblock %}

ecommerce/templates/contact_form.html
{% extends 'base.html' %}

{% block content %}
      <div class="row">

  <!-- Side Bar -->

        <div class="large-7 small-12 columns">
    <h1>Contact us</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
        <div class="field">
            {{ form.subject.errors }}
            <label for="id_subject">Subject:</label>
            {{ form.subject }}
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Your e-mail address:</label>
            {{ form.email }}
        </div>
        <div class="field">
            {{ form.message.errors }}
            <label for="id_message">Message:</label>
            {{ form.message }}
        </div>
        <button class="button">Submit</button>
    </form>
  </div>
  </div>  

{% endblock %}

ecommerce/templates/home.html
{% extends 'base.html' %}
{% block title %}JMD Seafoods | Home{% endblock %}
{% block content %}

    <!-- End Navigation -->

      <div class="row">

  <!-- Side Bar -->

        <div class="large-4 small-12 columns">

          <img src="static/img/jmd-logo.png">

          <div class="hide-for-small panel">
            <h3>JMD Seafoods Inc.</h3>
            <h5 class="subheader">
                Welcome to JMD Seafoods Inc., Where we sell fresh fishes. Please feel free to explore our website. Have a nice day!
            </h5>
          </div>



        </div>

    <!-- End Side Bar -->


    <!-- Thumbnails -->

    <div class="large-8 columns">
      <div class="row">
      {% for p in p %}
        <div class="large-4 small-6 columns">
          <a href="product/{{ p.slug }}">
            {% if p.image %}
              <img src="{{ p.image.url }}">
            {% else %}
              <img src="http://placehold.it/500x500&text=Thumbnail">
            {% endif %}
            <div class="panel">
              <h5>{{ p.name }}</h5>
              <h6 class="subheader">P {{ p.price }}</h6>
          </a>
            </div>
        </div>
      {% endfor %}
      </div>
    </div>

    <!-- End Thumbnails -->


    <!-- Managed By -->
          <div class="row">
            <div class="large-12 columns">
              <div class="panel">
                <div class="row">

                  <div class="large-2 small-6 columns">
                    <img src="http://placehold.it/300x300&text=Site Owner">
                  </div>

                  <div class="large-10 small-6 columns">
                    <strong>This Site Is Managed By<hr/></strong>

                    Ecom Dev't Team
                    <p>
                        <ul>
                            <li>Joanel Divinagracia - Developer</li>
                            <li>Arveen Landa - Developer/Designer</li>
                            <li>Kevin Gallarin - Designer</li>
                            <li>Carlo Baltazar - Developer</li>
                        </ul>

                    </p>
                  </div>

                </div>
              </div>
            </div>

    <!-- End Managed By -->

          </div>
        </div>
      </div>
    </div>
  </div>






{% endblock %}

ecommerce/templates/my_account.html
{% extends "catalog.html" %}

{% block content %}
<h1>My Account</h1>
<strong>Welcome, {{ name|capfirst }}!</strong>
<br /><br />
<fieldset class="my_account">
	<legend>Order History</legend>
	{% for order in orders %}
		<a href="{{ order.get_absolute_url }}">
		Order #{{ order.id }} - {{ order.date|date }}  (view)
		</a><br />
	{% empty %}
		You have no past orders.
	{% endfor %}
</fieldset>
<br />
<fieldset class="my_account">
	<legend>Account Settings</legend>
	<ul>
	<li><a href="/password_change">Change Password</a></li>
	<li><a href="{% url order_info %}">Edit Billing/Shipping Information</a></li>
	</ul>
</fieldset>
{% endblock %}